# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field


class PrivateKeyItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    name: Optional[str] = None
    data: Optional[str] = None
    """
    Base64 encoded private key.
    """
    certificate_chain: Optional[list[str]] = Field(None, alias='certificate-chain')
    """
    A certificate chain for this public key. Each certificate is an X.509 v3 certificate
    structure as specified by RFC5280, encoded using the Base64 format.
    """


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    private_key: Optional[list[PrivateKeyItem]] = Field(None, alias='private-key')
    """
    A private key.
    """
