# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from enum import Enum


class Datastore(Enum):
    CONFIGURATION = 'CONFIGURATION'
    OPERATIONAL = 'OPERATIONAL'


class Operation(Enum):
    merge = 'merge'
    replace = 'replace'


class SourceDatastore(Enum):
    CONFIGURATION = 'CONFIGURATION'
    OPERATIONAL = 'OPERATIONAL'


class TargetDatastore(Enum):
    CONFIGURATION = 'CONFIGURATION'
    OPERATIONAL = 'OPERATIONAL'
