# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from . import SourceDatastore
from . import TargetDatastore


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    changes: Optional[list[str]] = None
    """
    Result of diff between source and target YIID paths in a git like style.
    """


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    source_datastore: Optional[SourceDatastore] = Field(None, alias='source-datastore')
    target_datastore: Optional[TargetDatastore] = Field(None, alias='target-datastore')
    target_path: str = Field(..., alias='target-path')
    """
    Target path YIID.
    """
    source_path: str = Field(..., alias='source-path')
    """
    Source path YIID.
    """
