# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from enum import Enum


class DataChangeScope(Enum):
    BASE = 'BASE'
    ONE = 'ONE'
    SUBTREE = 'SUBTREE'
