# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from enum import Enum


class JournalLevel(Enum):
    command_only = 'command-only'
    extended = 'extended'


class ParsingEngine(Enum):
    batch_parser = 'batch-parser'
    tree_parser = 'tree-parser'
    one_line_parser = 'one-line-parser'


class TransportTypeEnumeration(Enum):
    ssh = 'ssh'
    telnet = 'telnet'
