# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from ... import logging


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    hidden_http_headers: Optional[list[str]] = Field(None, alias='hidden-http-headers')
    """
    List of HTTP headers (names of the headers) which content is hidden in the logs.
    Names of the HTTP headers are not case-sensitive.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    message: Optional[str] = None
    """
    Information message about state of operation.
    """
    status: logging.RpcStatus
