# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from ... import logging
from . import HttpMethod


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    hidden_http_methods: Optional[list[HttpMethod]] = Field(
        None, alias='hidden-http-methods'
    )
    """
    HTTP requests (and associated HTTP responses) are not logged if request's HTTP method is set
    to one of the methods in this list.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    message: Optional[str] = None
    """
    Information message about state of operation.
    """
    status: logging.RpcStatus
