# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from . import DataChangeScope


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    subscription_id: str = Field(..., alias='subscription-id')
    """
    Unique identifier of the subscription.
    """


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    subtree_path: str = Field(..., alias='subtree-path')
    """
    Identifier of the subtree in the data-tree expressed as relative path.
    """
    node_id: Optional[str] = Field(None, alias='node-id')
    """
    Identifier of 'network-topology/topology/node' list entry.
    """
    data_change_scope: Optional[DataChangeScope] = Field(
        None, alias='data-change-scope'
    )
    topology_id: str = Field(..., alias='topology-id')
    """
    Identifier of 'network-topology/topology' list entry.
    """
