# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from . import MountType


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    nodes: Optional[list[str]] = None
    """
    List of node identifiers.
    """


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    mount_type: Optional[MountType] = Field(None, alias='mount-type')
