# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from ...frinx import types
from . import ConnectionType


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node_id: str = Field(..., alias='node-id')
    """
    Node identifier of CLI/NETCONF node.
    """
    connection_type: Optional[ConnectionType] = Field(None, alias='connection-type')


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    error_message: Optional[str] = Field(None, alias='error-message')
    """
    Message that described occurred error during invocation of operation.
    """
    status: types.OperationResultType
