# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    wait_for_output_timer: Optional[int] = Field(
        None, alias='wait-for-output-timer', ge=0, le=65535
    )
    """
    If no output is received during this time, then execute next command.
    Commands are sent without waiting for their echo.
    """
    error_check: Optional[bool] = Field(None, alias='error-check')
    """
    Flag for determine whether error handling will be enabled or not
    """
    command: str
    """
    Input configuration snippet (one or multiple commands separated by newline).
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    status: str
    """
    Status of the executed RPC.
    """
