# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Field


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    subscription_id: str = Field(..., alias='subscription-id')
    """
    Unique identifier of the subscription.
    """
