# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from ...frinx import types


class TargetNodes(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node: Optional[list[str]] = None


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    target_nodes: Optional[TargetNodes] = Field(
        None,
        alias='target-nodes',
        title='uniconfig.manager.targetuniconfigunistorenodesfields.TargetNodes',
    )


class Change(BaseModel):
    class Config:
        allow_population_by_field_name = True

    data: Optional[str] = None
    """
    Changes on the specified path in a git like style.
    """
    path: Optional[str] = None
    """
    Instance-identifier of updated data node.
    """


class NodeResultItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    changes: Optional[list[Change]] = None
    """
    All changes that happened between intended and actual uniconfig node
    """
    node_id: Optional[str] = Field(None, alias='node-id')
    error_type: Optional[types.ErrorType] = Field(None, alias='error-type')
    error_message: Optional[str] = Field(None, alias='error-message')
    """
    Error message describing cause of error.
    """
    status: types.OperationResultType


class NodeResults(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node_result: Optional[list[NodeResultItem]] = Field(None, alias='node-result')
    """
    Differences between intended and actual uniconfig node in a git like style.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    error_message: Optional[str] = Field(None, alias='error-message')
    """
    Error message that describe overall problem.
    """
    node_results: Optional[NodeResults] = Field(
        None,
        alias='node-results',
        title='uniconfig.manager.calculategitlikediffoutputfields.NodeResults',
    )
    """
    Individual result of calculate-diff for given nodes.
    """
    overall_status: types.OperationResultType = Field(..., alias='overall-status')
