# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    encryption_enabled: bool = Field(..., alias='encryption-enabled')
    """
    Is encryption enabled.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    encryption_enabled_actual_status: Optional[bool] = Field(
        None, alias='encryption-enabled-actual-status'
    )
    """
    Actual encryption enabled status (true or false).
    """
