# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from enum import Enum


class EditConfigTestOption(Enum):
    set = 'set'
    test_only = 'test-only'
    test_then_set = 'test-then-set'
