# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    yang_repository: Optional[str] = Field(None, alias='yang-repository')
    """
    Name of yang-repository used for upgrading of templates.
    It contains identifier of the YANG schema repository.
    Default value is latest configured YANG repository.
    """
    upgraded_template_name: Optional[str] = Field(None, alias='upgraded-template-name')
    """
    Identifier of the upgraded template. Default value is input 'template-name'.
    """
    template_name: str = Field(..., alias='template-name')
    """
    Identifier of the template.
    """
