# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml
#   timestamp: 2023-08-03T07:32:17+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Snapshot:
    name: Optional[str] = None
    nodes: Optional[list[str]] = None
    creation_time: Optional[str] = None
