# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    jsonb_path_query: str = Field(..., alias='jsonb-path-query')
    """
    JSON-path used for selection and filtering of elements inside node configuration.
    Only elements that are selected by this path are returned in the RPC output.
    """
    node_id: str = Field(..., alias='node-id')
    """
    Node identifier.
    """
    topology_id: str = Field(..., alias='topology-id')
    """
    Topology identifier.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    config: Optional[list[str]] = None
    """
    All JSON elements returned by input JSON path.
    """
