# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from enum import Enum


class DataTreeOperation(Enum):
    merge = 'merge'
    replace = 'replace'
    remove = 'remove'


class ErrorType(Enum):
    no_connection = 'no-connection'
    device_processing_error = 'device-processing-error'
    uniconfig_error = 'uniconfig-error'
    cli_error = 'cli-error'
    netconf_error = 'netconf-error'


class OperationResultType(Enum):
    complete = 'complete'
    fail = 'fail'
