# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from . import SourceDatastore
from . import TargetDatastore


class DeletedDatum(BaseModel):
    class Config:
        allow_population_by_field_name = True

    data: Optional[str] = None
    path: Optional[str] = None
    """
    Instance-identifier of deleted data node.
    """


class CreatedDatum(BaseModel):
    class Config:
        allow_population_by_field_name = True

    data: Optional[str] = None
    path: Optional[str] = None
    """
    Instance-identifier of created data node.
    """


class UpdatedDatum(BaseModel):
    class Config:
        allow_population_by_field_name = True

    path_actual: Optional[str] = Field(None, alias='path-actual')
    """
    Instance-identifier of updated data node.
    """
    path_intended: Optional[str] = Field(None, alias='path-intended')
    """
    Instance-identifier of updated data node.
    """
    data_intended: Optional[str] = Field(None, alias='data-intended')
    data_actual: Optional[str] = Field(None, alias='data-actual')


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    deleted_data: Optional[list[DeletedDatum]] = Field(None, alias='deleted-data')
    """
    Removed intended configuration against actual.
    """
    created_data: Optional[list[CreatedDatum]] = Field(None, alias='created-data')
    """
    Created intended configuration against actual.
    """
    updated_data: Optional[list[UpdatedDatum]] = Field(None, alias='updated-data')
    """
    Updated intended configuration against actual.
    """


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    source_datastore: Optional[SourceDatastore] = Field(None, alias='source-datastore')
    target_datastore: Optional[TargetDatastore] = Field(None, alias='target-datastore')
    target_path: str = Field(..., alias='target-path')
    """
    Target path YIID.
    """
    source_path: str = Field(..., alias='source-path')
    """
    Source path YIID.
    """
