# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from enum import Enum


class RepositoryCreationStatus(Enum):
    success = 'success'
    failed = 'failed'
