# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Field

from ...frinx import types


class TargetNodes(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node: Optional[list[str]] = None


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    target_nodes: Optional[TargetNodes] = Field(
        None,
        alias='target-nodes',
        title='uniconfig.manager.targetuniconfigunistorenodesfields.TargetNodes',
    )


class CreatedDatum(BaseModel):
    class Config:
        allow_population_by_field_name = True

    data: Optional[str] = None
    path: Optional[str] = None
    """
    Instance-identifier of created data node.
    """


class UpdatedDatum(BaseModel):
    class Config:
        allow_population_by_field_name = True

    path: Optional[str] = None
    """
    Instance-identifier of updated data node.
    """
    data_intended: Optional[str] = Field(None, alias='data-intended')
    data_actual: Optional[str] = Field(None, alias='data-actual')


class DeletedDatum(BaseModel):
    class Config:
        allow_population_by_field_name = True

    data: Optional[str] = None
    path: Optional[str] = None
    """
    Instance-identifier of deleted data node.
    """


class ReorderedList(BaseModel):
    class Config:
        allow_population_by_field_name = True

    path: Optional[str] = None
    """
    Instance-identifier of reordered list.
    """
    intended_list_keys: Optional[str] = Field(None, alias='intended-list-keys')
    actual_list_keys: Optional[str] = Field(None, alias='actual-list-keys')


class NodeResultItem(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node_id: Optional[str] = Field(None, alias='node-id')
    created_data: Optional[list[CreatedDatum]] = Field(None, alias='created-data')
    """
    Created intended configuration against actual.
    """
    error_message: Optional[str] = Field(None, alias='error-message')
    """
    Error message describing cause of error.
    """
    updated_data: Optional[list[UpdatedDatum]] = Field(None, alias='updated-data')
    """
    Updated intended configuration against actual.
    """
    deleted_data: Optional[list[DeletedDatum]] = Field(None, alias='deleted-data')
    """
    Removed intended configuration against actual.
    """
    error_type: Optional[types.ErrorType] = Field(None, alias='error-type')
    status: types.OperationResultType
    reordered_lists: Optional[list[ReorderedList]] = Field(
        None, alias='reordered-lists'
    )
    """
    Reordered intended list against actual.
    """


class NodeResults(BaseModel):
    class Config:
        allow_population_by_field_name = True

    node_result: Optional[list[NodeResultItem]] = Field(None, alias='node-result')
    """
    Differences between intended and actual uniconfig node.
    """


class Output(BaseModel):
    class Config:
        allow_population_by_field_name = True

    error_message: Optional[str] = Field(None, alias='error-message')
    """
    Error message that describe overall problem.
    """
    node_results: Optional[NodeResults] = Field(
        None,
        alias='node-results',
        title='uniconfig.manager.calculatediffoutputfields.NodeResults',
    )
    """
    Individual result of calculate-diff for given nodes.
    """
    overall_status: types.OperationResultType = Field(..., alias='overall-status')
