name: pr-check

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test
          check_filenames: true
          check_hidden: false

  code-validate:
    name: Validate code
    runs-on: ubuntu-latest
    outputs:
      python-api-packages: ${{ steps.python.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1
    - uses: jpetrucciani/mypy-check@master
