name: pr-check

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: test
          check_filenames: true
          check_hidden: false

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      python-api-packages: ${{ steps.python.outputs.changes }}
    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1

#    - uses: dorny/paths-filter@v2
#      id: python
#      with:
#        filters: |
#          inventory:
#            - 'inventory/python/**'
#          resource-manager/python:
#            - 'resource-manager/python/**'
#          schellar:
#            - 'schellar/python/**'
#          topology-discovery/python:
#            - 'topology-discovery/python/**'
#          uniconfig:
#            - 'uniconfig/python/**'

#  python-api-check:
#    needs: changes
#    strategy:
#      matrix:
#        package: ${{ fromJSON(needs.changes.outputs.python-api-packages) }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Echo module
#        run: cd ${{ matrix.package }}/python