# generated by datamodel-codegen:
#   filename:  uniconfigV3.yaml

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Input(BaseModel):
    class Config:
        allow_population_by_field_name = True

    filter: Optional[str] = None
    """
    An optional parameter that indicates which subset of all
    possible events is of interest. The format of this
    parameter is the same as that of the filter parameter
    in the NETCONF protocol operations. If not present,
    all events not precluded by other parameters will
    be sent.
    """
    stopTime: Optional[str] = None  # noqa: N815
    """
    An optional parameter used with the optional replay
    feature to indicate the newest notifications of
    interest. If stop time is not present, the notifications
    will continue until the subscription is terminated.
    Must be used with startTime.
    """
    startTime: Optional[str] = None  # noqa: N815
    """
    A parameter used to trigger the replay feature and
    indicates that the replay should start at the time
    specified. If start time is not present, this is not a
    replay subscription.
    """
    stream: Optional[str] = None
    """
    An optional parameter that indicates which stream of events
    is of interest. If not present, then events in the default
    NETCONF stream will be sent.
    """
